### ISSUE TITLE
(experimental) text should be removed from group and command descriptions

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli-db2-plugin#10]
The Db2 plugin should no longer be in an experimental state. Therefore the `(experimental)` text should be removed from Db2 group and command descriptions. If something needs to be done before removing the `(experimental)` text, please advise.

![image](https://user-images.githubusercontent.com/35504792/51618800-eb502200-1efc-11e9-9b18-d1b58164de77.png)
![image](https://user-images.githubusercontent.com/35504792/51618822-f73be400-1efc-11e9-9bde-92c0fb150ee9.png)
![image](https://user-images.githubusercontent.com/35504792/51618878-1175c200-1efd-11e9-903b-152746ed007c.png)

**Comment by nurra01** [comment]
fixed by pull request #13
