### ISSUE TITLE
Improve response message when executing SELECT * FROM a table that does not exist

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli-db2-plugin#31]
The following command error is returned when issuing SELECT * FROM a table that does not exist. 

![image](https://user-images.githubusercontent.com/35504792/61328810-d7211980-a7e9-11e9-926c-5ed9e1dfe359.png)

When running the command against an existing table, the output is as expected.

Node version: 10.13.0
Npm version: 6.4.1
Zowe CLI version: 5.9.1
Db2-plugin version: 3.0.1

**Comment by vasev01** [comment]
Hi Mike,
This issue is resolved in version 3.0.2, see PR #27
