### ISSUE TITLE
Incorrect license location in documentation

### ISSUE THREAD

**Issue by markjhollands** [zowe/zowe-cli-db2-plugin#61]
In this section of the installation documentation:
https://docs.zowe.org/stable/user-guide/cli-db2plugin.html#addressing-the-license-requirement

it says to place the license file here:
```
<zowe_home>/plugins/installed/lib/node_modules/@zowe/db2/node_modules/ibm_db/installer/clidriver/license
```
(and similar for Windows)

The license location should be here:
```
<zowe_home>/plugins/installed/lib/node_modules/@zowe/db2-for-zowe-cli/node_modules/ibm_db/installer/clidriver/license
```
(and similar for Windows)

**Comment by mpanch59** [comment]
started to work on this

**Comment by Joe-Winchester** [comment]
Closed with https://github.com/zowe/docs-site/pull/1477
