### ISSUE TITLE
Incorrect Db2 Connect license file version in documentation

### ISSUE THREAD

**Issue by markjhollands** [zowe/zowe-cli-db2-plugin#62]
In this section of the documentation: https://docs.zowe.org/stable/user-guide/cli-db2plugin.html#addressing-the-license-requirement

it states "The license must be of version 11.1 if the Db2 server is not `db2connectactivated`"

In the `ibm_db` node module (which is what actually uses the license file) documentation it states: "[...] However, if you want to use node-ibm_db against DB2 for z/OS or DB2 for i(AS400) Servers, you must have db2connect license of version 11.5 if server is not `db2connectactivated` [...]". (https://www.npmjs.com/package/ibm_db#for-zos-and-iseries-connectivity)

I have only got this working with an 11.5 license file, so I believe this should be updated in the Zowe docs. This may have been caused by an update to the Db2 CLI Driver since the initial release of the Zowe Db2 plugin.

**Comment by mpanch59** [comment]
please assign issue to me , have updated doc and created pull request

**Comment by Joe-Winchester** [comment]
Fixed with https://github.com/zowe/docs-site/pull/1477
