### ISSUE TITLE
No help for SQL0805N error in documentation

### ISSUE THREAD

**Issue by markjhollands** [zowe/zowe-cli-db2-plugin#63]
While installing the Db2 plugin, a number of users have experienced the following error when trying to use the plugin:
```
$ zowe db2 execute sql --query "select * from sysibm.SYSPACKAGE where pkgname like 'SQLC2H20'"
Command Error:
DB2 ODBC Driver Error: [node-ibm_db] Error in ODBCConnection::QuerySync while executing query.
Error Details:
Error:    [IBM][CLI Driver][DB2] SQL0805N  Package "DSNV112E.NULLID.SYSSH200.5359534C564C3031" was not found.  SQLSTATE=51002
SQLCODE:  -805
SQLSTATE: 51002
```

This is caused by a failure to run a bind enabling the Db2 CLI to be used against the database. In the `ibm_db` NPM documentation (the node module used for Db2 connectivity by the Zowe Db2 CLI), it provides some help regarding this error: https://www.npmjs.com/package/ibm_db#for-missing-packagebinding-issue

Could we also include this help in the Zowe docs for the plugin? I think this could be a common error, and is worth flagging as a gotcha to users.

**Comment by AndrewTwydell** [comment]
There is now this section in the docs that I think covers this bind requirement issue.

https://docs.zowe.org/stable/user-guide/cli-db2plugin.html#sql0805n-database-bind
https://github.com/zowe/docs-site/pull/1517

@MikeBauerCA Can this issue be closed??

**Comment by MikeBauerCA** [comment]
Yes, thanks!
