### ISSUE TITLE
Export table does not generate statement separator

### ISSUE THREAD

**Issue by ToineMichielseBroadcom** [zowe/zowe-cli-db2-plugin#65]
The current version does NOT generate an ‘end-of-statement’ character.  As a result, the output file would have to be edited in order for it to be useful with for example zowe excute sql to use the generated statements. Perhaps it makes sense to add an option to generate or suppress the option.

**Comment by MikeBauerCA** [comment]
@AndrewTwydell could you please take a look at this one?

**Comment by AndrewTwydell** [comment]
@MikeBauerCA Of course! I'll take a look at that this week.
